import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
  },
  moodCard: {
    backgroundColor: 'rgba(255,255,255,0.25)',
    borderRadius: 20,
    padding: 30,
    marginBottom: 20,
  },
  title: {
    fontSize: 32,
    fontWeight: '800',
    color: '#2D2D2D',
    marginBottom: 25,
    alignSelf: 'center',
  },
  moodButtons: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 20,
    marginTop: 10,
    marginBottom: 24,
  },
  moodButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f7fafc',
    borderRadius: 24,
    paddingVertical: 18,
    paddingHorizontal: 22,
    marginBottom: 0,
    marginHorizontal: 0,
    minWidth: 120,
    minHeight: 64,
    shadowColor: '#22543d',
    shadowOpacity: 0.10,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 2,
    borderColor: '#e2e8f0',
  },
  flexGrow: {
    flex: 1,
  },
  moodEmoji: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 18,
    backgroundColor: '#fff',
    shadowColor: '#b7e4c7',
    shadowOpacity: 0.10,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    elevation: 2,
    overflow: 'hidden',
  },
  emojiText: {
    fontSize: 44,
    textAlign: 'center',
    color: '#22543d',
    width: 60,
    height: 60,
    textAlignVertical: 'center',
    lineHeight: 60,
    includeFontPadding: false,
  },
  moodText: {
    fontSize: 26,
    fontWeight: '600',
    color: '#22543d',
    letterSpacing: 0.2,
    opacity: 0.92,
  },
  happy: {
    backgroundColor: '#f0fff4',
    borderColor: '#68d391',
    borderWidth: 0,
  },
  neutral: {
    backgroundColor: '#fffaf0',
    borderColor: '#fbb6ce',
    borderWidth: 0,
  },
  sad: {
    backgroundColor: '#ebf8ff',
    borderColor: '#90cdf4',
    borderWidth: 0,
  },
  noInternetCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 32,
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    minWidth: 260,
    maxWidth: 320,
    zIndex: 2,
  },
  noInternetEmoji: {
    fontSize: 40,
    marginBottom: 12,
  },
  noInternetTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: 8,
    textAlign: 'center',
  },
  noInternetMsg: {
    fontSize: 16,
    color: '#555',
    textAlign: 'center',
    marginBottom: 16,
  },
  noInternetWait: {
    fontSize: 14,
    color: '#aaa',
    textAlign: 'center',
  },
  selectedMood: {
    backgroundColor: 'rgba(232, 230, 255, 1)',
    borderColor: 'rgba(139, 126, 216, 0.6)',
  },
});

export default styles;
